### ISSUE TITLE
pyserial setTimeout issue

### ISSUE THREAD

**Issue by vrmp** [travisgoodspeed/goodfet#23]
previously (half year ago?) working goodfet software throws now the following exception:

```
Traceback (most recent call last):
  File "/usr/local/bin/goodfet.monitor", line 27, in <module>
    client.serInit()
  File "/home/user/soft/goodfet/client/GoodFET.py", line 133, in serInit
    self.pyserInit(port,timeout,attemptlimit);
  File "/home/user/soft/goodfet/client/GoodFET.py", line 264, in pyserInit
    self.serialport.setTimeout(12);
AttributeError: 'Serial' object has no attribute 'setTimeout'

```
platform is linux (debian jessie), nothing really changed, only regular security  updates (including python). updating the goodfet from git does not help (same error).

hardware is working, because commenting out the line "264" makes most things work (ledtest, info, etc)

**Comment by travisgoodspeed** [comment]
Which version of python-serial are you running?

**Comment by bensya** [comment]
I met the same issue!!
Meanwhile, goodfet.bsl does't support goodthopter12 board!!!

**Comment by bensya** [comment]
The BOARDS did not define the Goodthopter12!

BOARDS = {
    #'apimote': "apimote1",	# .hex not uploaded yet
    #'apimote1': "apimote1",
    #'apimote2': "apimote2",
    #'apimote3': "apimote2",
    #'apimote4': "apimote2",
    'facedancer10': "facedancer10",
    'facedancer11': "facedancer11",
    'facedancer20': "facedancer20",
    'facedancer21': "facedancer21",
    'goodfet10': "goodfet11", # 1612
    'goodfet11': "goodfet11", # 1612
    'goodfet20': "goodfet11", # 1612
    'goodfet21': "goodfet41", # 2618
    'goodfet22': "goodfet41", # 2618 w/ADG1634
    'goodfet30': "goodfet31", # 2274
    'goodfet31': "goodfet31", # 2274
    'goodfet31l': "goodfet31", # 2274 (QFN)
    'goodfet32': "goodfet31", # 2274
    'goodfet40': "goodfet41", # 2618
    'goodfet41': "goodfet41", # 2618
    'goodfet42': "goodfet42", # 2618
    'badfet20': "goodfet41", # 2618 w/74HC4053
    'goodthopter10': "goodthopter10",
    'goodthopter11': "goodthopter11",
    'telosb': "telosb",
    'telosbbt': "telosb",
    'z1': "z1",
    'zolertiaz1': "z1",
}

**Comment by bensya** [comment]
I compiled the code and run the command as follows to download goodthopter12 to MCU:
goodfet.bsl  -e -p goodthopter12.hex
It appeared program successfully. 
After that, I run goodfet.monitor test, it will appear
AttributeError: 'Serial' object has no attribute 'setTimeout'

After comment commenting out the line "264" makes command work , but still have many issues:
it prompt: 
See the GoodFET FAQ about missing info flash.
Performing monitor self-test.
Warning: waiting for serial read timed out (most likely).
ERROR, P1OUT not cleared.
Warning: waiting for serial read timed out (most likely).
Echo test failed.
Warning: waiting for serial read timed out (most likely).
Warning: waiting for serial read timed out (most likely).
Warning: waiting for serial read timed out (most likely).
Warning: waiting for serial read timed out (most likely).
ERROR Fetched 0100, 0302
Warning: waiting for serial read timed out (most likely).
Warning: waiting for serial read timed out (most likely).
ERROR, P1OUT not cleared.
Warning: waiting for serial read timed out (most likely).
Warning: waiting for serial read timed out (most likely).

Anyone can help me?

**Comment by bensya** [comment]
Run the command " goodfet.bsl --fromweb", it seems program successfully. But the goodthopther still not working. Cannot run goodfet.monitor test probly

Use -h for help
Use --fromweb to upgrade a GoodFET.
Unknown board specified.  Try board=goodfet41 if unsure.
Press Ctrl+C to cancel, or Enter to continue using unknown board.
MSP430 Bootstrap Loader Version: 1.39-goodfet-8
Invoking BSL...
Transmit default password ...
Use -h for help
Use --fromweb to upgrade a GoodFET.
Unknown board specified.  Try board=goodfet41 if unsure.
Press Ctrl+C to cancel, or Enter to continue using unknown board.
MSP430 Bootstrap Loader Version: 1.39-goodfet-8
Invoking BSL...
Transmit default password ...
Current bootstrap loader version: 2.2 (Device ID: f227)
Checking for info flash...  None.
Look at contrib/infos/README.txt for better performance.
Grabbing goodthopter12 firmware from http://goodfet.sourceforge.net/dist/goodthopter12.hex
Mass Erase...
Transmit default password ...
Invoking BSL...
Transmit default password ...
Current bootstrap loader version: 2.2 (Device ID: f227)
Program ...
4994 bytes programmed.

**Comment by rmspeers** [comment]
What was your board environment variable set to? Can you show the command line if you set it there? It seems like it didn't recognize it but later in the output it looks like it did get it?

**Comment by bensya** [comment]
I set  export board=goodthopter12, and it appears successfully.
Right, it didn't recognize it as goodfet.bsl does not include this board.
I specify the hex files to flash the board.

**Comment by rmspeers** [comment]
It appears from the output above that it did find the hex files on the website and it grabbed them. I can't tell for sure though as I don't see the command lines entered.
However, upon looking more I think that the issue may be with your pySerial and GoodFET versions. You don't want to have to comment out the line of setTimeout, you want to work with a version of GoodFET and pySerial that make that available to you.

**Comment by bensya** [comment]
thanks rmsspeers!
could u let know which version of pySerial and GoodFET is correct? and how to check it?

**Comment by rmspeers** [comment]
FYI: Usually the message posted above indicates that you're using a pyusb that doesn't support the timeout.
`AttributeError: 'Serial' object has no attribute 'setTimeout'`
Changing to self.serialport.timeout = 12 or similar should work.

**Comment by travisgoodspeed** [comment]
Was this not fixed by #25?

@rmspeers Do you have time to chase this down and apply a fix?

Cheers from Philly,
--Travis

**Comment by rmspeers** [comment]
Sure -- will follow up.
@bensya  - Please let me know if this is still happening for you, and your pySerial version. I'll work this out with you in a branch and then we'll merge once it's working.

**Comment by bensya** [comment]
Thanks rmspeers, I will check later today. My pySerial version is 3.1.1.  Linux version: 4.7.0-rc3; Python version: 2.7.11
