### ISSUE TITLE
Chip ID is 0xffff, implying a wiring problem.

### ISSUE THREAD

**Issue by tiagosiebler** [travisgoodspeed/goodfet#54]
Hi Travis & anyone else,

Trying to tinker with hardware stuff for the first time, using an im-me as well as a goodfet42 purchased from thepihut: 
https://thepihut.com/products/goodfet-v42-by-travis-goodspeed

Followed this wiring from your flickr albums (I added colouring to match my wires, just to make sure I'm not making a mistake):
<img width="997" alt="goodfet - colouring" src="https://user-images.githubusercontent.com/14090872/168836426-f3dc7a80-bca1-463f-99d2-66a2cd2aa74c.png">

I did use the power wire too, since I'm powering the device via the connected goodfet. Here's my wiring:
![2022-05-17 15 35 59](https://user-images.githubusercontent.com/14090872/168837594-2f400fb5-5457-48a4-a13c-8a22bdb0b4a1.jpg)

Hooked up to the same pins of the goodfet:
![2022-05-17 15 36 10](https://user-images.githubusercontent.com/14090872/168837648-4b37947e-ba20-451b-862c-51b0273d6a31.jpg)

The im-me does power on, when I connect the goodfet to my mac:
![2022-05-17 15 36 15](https://user-images.githubusercontent.com/14090872/168837715-0d67bb90-0828-4b2a-8d8c-d5bf98815d14.jpg)

So far so good. Next I wanted to try flashing the LCD Test from your tutorial (as well as the other goodfet.cc commands just to try them):
https://travisgoodspeed.blogspot.com/2010/03/im-me-goodfet-wiring-tutorial.html

The goodfet repo readme says I need to set the client, though some parts mention a board env var, so I've just set both. When I try any command, such as this one:
```
client=goodfet42 board=goodfet42 goodfet.cc status
```

I see some information from the connected im-me (which disappears if I disconnect the im-me but reconnect the goodfet without it), but none of the commands seem to work because of the chip ID errors:
```
sh-3.2# client=goodfet42 board=goodfet42 goodfet.cc status
Chip ID is 0xffff, implying a wiring problem.
Status: erase_busy pcon_idle cpu_halted pm0 halt_status locked oscstable overflow 
```

Any ideas/pointers/nudges on what I may be missing? Are my solders that bad? Any ideas which one, if that's the case?

**Comment by tiagosiebler** [comment]
Interesting, so if I include the reset flag, on the second retry the dump works:
```shell
sh-3.2# goodfet.bsl --dumpinfo -r
Use -h for help
Use --fromweb to upgrade a GoodFET.
MSP430 Bootstrap Loader Version: 1.39-goodfet-8
Reset device ...
Invoking BSL...
Transmit default password ...
Use -h for help
Use --fromweb to upgrade a GoodFET.
MSP430 Bootstrap Loader Version: 1.39-goodfet-8
Reset device ...
Invoking BSL...
Transmit default password ...
Traceback (most recent call last):
  File "/usr/local/bin/goodfet.bsl", line 1987, in <module>
    main(0);
  File "/usr/local/bin/goodfet.bsl", line 1942, in main
    bsl.actionStartBSL(bslreset=reset)
  File "/usr/local/bin/goodfet.bsl", line 1166, in actionStartBSL
    self.txPasswd(self.passwd)                  #transmit password
  File "/usr/local/bin/goodfet.bsl", line 1136, in txPasswd
    wait=wait)           #if wait is 1, try to sync forever
  File "/usr/local/bin/goodfet.bsl", line 801, in bslTxRx
    rxFrame = self.comTxRx(cmd, dataOut, len(dataOut))  #Send frame
  File "/usr/local/bin/goodfet.bsl", line 480, in comTxRx
    rxHeader, rxNum = self.comRxHeader()        #receive header
  File "/usr/local/bin/goodfet.bsl", line 386, in comRxHeader
    if not hdr: raise BSLException("Timeout")
__main__.BSLException: Timeout


sh-3.2# goodfet.bsl --dumpinfo -r
Use -h for help
Use --fromweb to upgrade a GoodFET.
MSP430 Bootstrap Loader Version: 1.39-goodfet-8
Reset device ...
Invoking BSL...
Transmit default password ...
Current bootstrap loader version: 2.13 (Device ID: f26f)
@1000
ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
q

```

Now if I run goodfet.cc status, I get an error about missing flash:
```
sh-3.2# goodfet.cc status
See the GoodFET FAQ about missing info flash.
```

So I run the fromweb update:
```
h-3.2# goodfet.bsl --fromweb
Use -h for help
Use --fromweb to upgrade a GoodFET.
MSP430 Bootstrap Loader Version: 1.39-goodfet-8
Invoking BSL...
Transmit default password ...
Current bootstrap loader version: 2.13 (Device ID: f26f)
Checking for info flash...  None.
Look at contrib/infos/README.txt for better performance.
Grabbing goodfet42 firmware from http://goodfet.sourceforge.net/dist/goodfet42.hex
Mass Erase...
Transmit default password ...
Invoking BSL...
Transmit default password ...
Current bootstrap loader version: 2.13 (Device ID: f26f)
Program ...
25842 bytes programmed.
```

Still goes back ot the same error:
```
sh-3.2# goodfet.cc status
See the GoodFET FAQ about missing info flash.
Chip ID is 0xffff, implying a wiring problem.
Status: erase_busy pcon_idle cpu_halted pm0 halt_status locked oscstable overflow 
```

Also if I try the fromweb call again, sometimes I get timeouts:
```
sh-3.2# goodfet.bsl --fromweb
Use -h for help
Use --fromweb to upgrade a GoodFET.
MSP430 Bootstrap Loader Version: 1.39-goodfet-8
Invoking BSL...
Transmit default password ...
Use -h for help
Use --fromweb to upgrade a GoodFET.
MSP430 Bootstrap Loader Version: 1.39-goodfet-8
Invoking BSL...
Transmit default password ...
Traceback (most recent call last):
  File "/usr/local/bin/goodfet.bsl", line 1987, in <module>
    main(0);
  File "/usr/local/bin/goodfet.bsl", line 1887, in main
    bsl.actionStartBSL()
  File "/usr/local/bin/goodfet.bsl", line 1166, in actionStartBSL
    self.txPasswd(self.passwd)                  #transmit password
  File "/usr/local/bin/goodfet.bsl", line 1136, in txPasswd
    wait=wait)           #if wait is 1, try to sync forever
  File "/usr/local/bin/goodfet.bsl", line 801, in bslTxRx
    rxFrame = self.comTxRx(cmd, dataOut, len(dataOut))  #Send frame
  File "/usr/local/bin/goodfet.bsl", line 480, in comTxRx
    rxHeader, rxNum = self.comRxHeader()        #receive header
  File "/usr/local/bin/goodfet.bsl", line 386, in comRxHeader
    if not hdr: raise BSLException("Timeout")
__main__.BSLException: Timeout
```

goodfet.monitor info just hangs:
```
sh-3.2# goodfet.monitor info
See the GoodFET FAQ about missing info flash.
Tried 100 times to connect and failed.
Continuing to try forever.
```

I saw a faq mention about random crashes (although that's ubuntu), linking to this:
https://blog.thelifeofkenneth.com/2010/12/soldering-goodfet-31.html#software

Assumed it wasn't related but will take another look since it's timeout errors. Tomorrow, with a fresh mind. If anyone has any tips or suggestions, would warmly appreciate them. Thanks!

**Comment by tiagosiebler** [comment]
Still inconsistent progress sadly. Not sure how to better isolate the problem / where to focus, as I keep ending on square one when trying to use the goodfet.cc client. I did try running it in a ubuntu VM, to try and get a bit closer to how other people seem to have run this and fixed their issues. That didn't make a difference in results, so reverted back to testing in my host env (macbook).

This is no longer hanging:
```
sh-3.2# goodfet.monitor info
GoodFET with f26f MCU
Clocked at 0x8f85
```

This works too (and leds flash):
```
sh-3.2# goodfet.monitor testleds
Flashing LEDs
Flashed 1 LED.
```

The test seems to pass too (this has failed a few times before), after a bit of waiting and lots of led flashing:
```
sh-3.2# goodfet.monitor test
Performing monitor self-test.
Self-test complete.
```

But then the moment I try to call any of the goodfet.cc methods:
```
sh-3.2# goodfet.cc info
Chip ID is 0xffff, implying a wiring problem.
Ident   CCmissing/rffff/ps0x0400
Freq         0.000 MHz
RSSI    00
```

```
sh-3.2# goodfet.cc test
Chip ID is 0xffff, implying a wiring problem.
Tracing execution at startup.
Verifying that debugging a NOP doesn't affect the PC.
Checking pokes to XRAM.
Traceback (most recent call last):
  File "/usr/local/bin/goodfet.cc", line 400, in <module>
    client.test();
  File "/Volumes/Repositories/Public/Hardware/goodfet/client/GoodFETCC.py", line 732, in test
    for i in range(self.execbuf,self.execbuf+0x20):
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
```

I guess this is because CCident in goodfetcc.py always returns that empty chip ID 0xffff ? 

goodfet.bsl also doesn't work without providing -P firmware.hex:
```
sh-3.2# goodfet.bsl --dumpinfo          
Use -h for help
Use --fromweb to upgrade a GoodFET.
MSP430 Bootstrap Loader Version: 1.39-goodfet-8
Invoking BSL...
Transmit default password ...
Use -h for help
Use --fromweb to upgrade a GoodFET.
MSP430 Bootstrap Loader Version: 1.39-goodfet-8
Invoking BSL...
Transmit default password ...
Traceback (most recent call last):
  File "/usr/local/bin/goodfet.bsl", line 1987, in <module>
    main(0);
  File "/usr/local/bin/goodfet.bsl", line 1942, in main
    bsl.actionStartBSL(bslreset=reset)
  File "/usr/local/bin/goodfet.bsl", line 1166, in actionStartBSL
    self.txPasswd(self.passwd)                  #transmit password
  File "/usr/local/bin/goodfet.bsl", line 1136, in txPasswd
    wait=wait)           #if wait is 1, try to sync forever
  File "/usr/local/bin/goodfet.bsl", line 800, in bslTxRx
    self.bslSync(wait)                          #synchronize BSL
  File "/usr/local/bin/goodfet.bsl", line 759, in bslSync
    raise BSLException(self.ERR_BSL_SYNC)       #Sync. failed
__main__.BSLException: Bootstrap loader synchronization error (maybe you need -P)

sh-3.2# goodfet.bsl --dumpinfo -P goodfet42.hex 
Use -h for help
Use --fromweb to upgrade a GoodFET.
MSP430 Bootstrap Loader Version: 1.39-goodfet-8
Invoking BSL...
Transmit password ...
Current bootstrap loader version: 2.13 (Device ID: f26f)
@1000
ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
q
```

This does show some info while the connected im-me is powered by the goodfet:
```
sh-3.2# goodfet.cc erase
Chip ID is 0xffff, implying a wiring problem.
Status: erase_busy pcon_idle cpu_halted pm0 halt_status locked oscstable overflow 
Status: erase_busy pcon_idle cpu_halted pm0 halt_status locked oscstable overflow 
```

Does this point to an issue with the goodfet or the connected im-me? Any ideas on what I can explore to nudge this a step forward? Thanks!

**Comment by travisgoodspeed** [comment]
1. Does your IMME power up to the stock firmware screen while powered from the GoodFET?
2. Do not run the `erase` command until you've figured out the problem.  A partial erase can brick the CC1110.
3. goodfet.bsl seems less reliable than it should be.  Do you see any loose solder joints on the MSP430 or FTDI pins?

It's been twelve years since I've played with an IMME, so forgive me if I'm overlooking something obvious.

**Comment by tiagosiebler** [comment]
Also does this mean your more likely suspect is not the GoodFET itself, but rather either the connection to the IM-ME or the IM-ME itself?

**Comment by tiagosiebler** [comment]
Btw is this a typo, should this be `apps` instead of `app`? It only compiles after changing it to `apps` but I'm not sure if that's the intended variable here.

**Comment by tiagosiebler** [comment]
Finally stumbled my way into this post about the info flash:
https://travisgoodspeed.blogspot.com/2010/02/call-for-info-flash.html

Couple of commands later:
```
$ goodfet.bsl -e      
Use -h for help
Use --fromweb to upgrade a GoodFET.
MSP430 Bootstrap Loader Version: 1.39-goodfet-8
Invoking BSL...
Transmit default password ...
Current bootstrap loader version: 2.13 (Device ID: f26f)
Checking for info flash...  None.
Look at contrib/infos/README.txt for better performance.
Mass Erase...
Transmit default password ...
```

```
$ goodfet.bsl --dumpinfo
Use -h for help
Use --fromweb to upgrade a GoodFET.
MSP430 Bootstrap Loader Version: 1.39-goodfet-8
Invoking BSL...
Transmit default password ...
Current bootstrap loader version: 2.13 (Device ID: f26f)
@1000
ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
q

```

```
$ goodfet.bsl -e -p contrib/infos/2618-002.txt
MSP430 Bootstrap Loader Version: 1.39-goodfet-8
Invoking BSL...
Transmit default password ...
Current bootstrap loader version: 2.13 (Device ID: f26f)
Checking for info flash...  None.
Look at contrib/infos/README.txt for better performance.
Mass Erase...
Transmit default password ...
Invoking BSL...
Transmit default password ...
Current bootstrap loader version: 2.13 (Device ID: f26f)
Program ...
256 bytes programmed.
```

```
$ goodfet.bsl --dumpinfo                      
Use -h for help
Use --fromweb to upgrade a GoodFET.
MSP430 Bootstrap Loader Version: 1.39-goodfet-8
Invoking BSL...
Transmit default password ...
Current bootstrap loader version: 2.13 (Device ID: f26f)
@1000
aa 55 ff 3f cd ab aa 55 34 12 ff ff aa 55 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 51 84 fe 16 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 08 10 00 80 00 00 62 7f 81 0b b2 0d 8f 7f e4 06 35 08 fe 08 ff ff ff ff ff ff ff ff 01 08 97 8f 9a 8e 8f 8d d4 86 
q
```

```
$ goodfet.bsl -p firmware/goodfet.hex
MSP430 Bootstrap Loader Version: 1.39-goodfet-8
Invoking BSL...
Transmit default password ...
Current bootstrap loader version: 2.13 (Device ID: f26f)
Program ...
26408 bytes programmed.
```

The moment I add the firmware, dumpinfo fails UNLESS I include -P firmware:
```
$ goodfet.bsl --dumpinfo
Use -h for help
Use --fromweb to upgrade a GoodFET.
MSP430 Bootstrap Loader Version: 1.39-goodfet-8
Invoking BSL...
Transmit default password ...
Use -h for help
Use --fromweb to upgrade a GoodFET.
MSP430 Bootstrap Loader Version: 1.39-goodfet-8
Invoking BSL...
Transmit default password ...
Traceback (most recent call last):
  File "/usr/local/bin/goodfet.bsl", line 1987, in <module>
    main(0);
  File "/usr/local/bin/goodfet.bsl", line 1942, in main
    bsl.actionStartBSL(bslreset=reset)
  File "/usr/local/bin/goodfet.bsl", line 1166, in actionStartBSL
    self.txPasswd(self.passwd)                  #transmit password
  File "/usr/local/bin/goodfet.bsl", line 1136, in txPasswd
    wait=wait)           #if wait is 1, try to sync forever
  File "/usr/local/bin/goodfet.bsl", line 800, in bslTxRx
    self.bslSync(wait)                          #synchronize BSL
  File "/usr/local/bin/goodfet.bsl", line 759, in bslSync
    raise BSLException(self.ERR_BSL_SYNC)       #Sync. failed
__main__.BSLException: Bootstrap loader synchronization error (maybe you need -P)




$ goodfet.bsl --dumpinfo -P firmware/goodfet.hex
Use -h for help
Use --fromweb to upgrade a GoodFET.
MSP430 Bootstrap Loader Version: 1.39-goodfet-8
Invoking BSL...
Transmit password ...
Current bootstrap loader version: 2.13 (Device ID: f26f)
@1000
aa 55 ff 3f cd ab aa 55 34 12 ff ff aa 55 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 51 84 fe 16 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 08 10 00 80 00 00 62 7f 81 0b b2 0d 8f 7f e4 06 35 08 fe 08 ff ff ff ff ff ff ff ff 01 08 97 8f 9a 8e 8f 8d d4 86 
q
```

Rest behaves as before though:
```
$ goodfet.monitor info
GoodFET with f26f MCU
Clocked at 0x8f97


$ goodfet.monitor testleds      
Flashing LEDs
Flashed 1 LED.

$ goodfet.cc status
Chip ID is 0xffff, implying a wiring problem.
Status: erase_busy pcon_idle cpu_halted pm0 halt_status locked oscstable overflow 
```

Back to the root with chip ID issues... does this refer to the connected device, or to a chip in the goodfet?

**Comment by tiagosiebler** [comment]
Sorry, another question - how do I know which 2618 info is the right one? Or is it purely trial & error?
![photo_2022-05-19 18 36 39](https://user-images.githubusercontent.com/14090872/169362943-ffad76fc-12b4-4358-8e9b-0270b936d1f1.jpeg)
